//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudyProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string ProfilePhoto { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Mission { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Adress { get; set; }
        public string About { get; set; }
        public string Experience { get; set; }
        public string Studies { get; set; }
        public string Skills { get; set; }
        public string Refs { get; set; }
        public string Hobies { get; set; }
        public string Certificiate { get; set; }
    }
}
